[package]
name = "rts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.2"
bevy-inspector-egui = "0.27.0"
bevy_mod_billboard = "0.7.0"
bevy_rapier3d = "0.27.0"
bevy_rts_camera = "0.8.1"
pathfinding = "4.11.0"

[profile.dev.package.bevy_rapier3d]
opt-level = 3

[profile.dev]
codegen-units = 1
opt-level = 3

[profile.release]
codegen-units = 1
opt-level = 3
